ProjetoCincoSolas/ProjetoCincoSolas/Controllers/SobreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoCincoSolas.Controllers
{
    public class SobreController : Controller
    {
        // GET: Sobre
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/js")

</head>
<body>
    <div class="super_container">
        <!-- Header -->
        <header class="header">
            <!-- Top Bar -->
            <div class="top_bar">
                <div class="top_bar_background" style="background-image:url(Imagens/top_bar.jpg)"></div>
                <div class="top_bar_container">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                                    <ul class="top_bar_contact_list">
                                        <li>
                                            <i class="fa fa-envelope" aria-hidden="true"></i>
                                            <div>E-mail: projetocincosolas@gmail.com</div>
                                        </li>
                                        <li>
                                            <i class="fa fa-phone" aria-hidden="true"></i>
                                            <div>+55 11 2636-5659</div>
                                        </li>
                                    </ul>
                                    <div class="top_bar_social ml-auto">
                                        <ul class="social_list">
                                            <li><a href="https://www.facebook.com/I.A.R.Altar/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                            @*<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>*@
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Header Content -->
            <div class="header_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                                <div class="logo_container">
                                    <a href="@Url.Action("Index", "Home")">
                                        <div class="logo"><img src="~/Imagens/logo.png" alt=""></div>
                                        <div class="logo_text">PROJETO CINCO SOLAS</div>
                                    </a>
                                </div>
                                <nav class="main_nav_contaner ml-auto">
                                    <ul class="main_nav">
                                        <li class="active"><a href="@Url.Action("Index", "Home")">início</a></li>
                                        <li><a href="@Url.Action("Index", "Sobre")">sobre</a></li>
                                        <li><a href="@Url.Action("Index", "ComentarioBiblico")">Comentários Bíblico</a></li>
                                        <li><a href="@Url.Action("Index", "DevocionalDiario")">Devocional</a></li>
                                        @*<li><a href="@Url.Action("Index", "EstudoBiblico")">Estudo Bíblico</a></li>*@
                                        @*
                                            <li><a href="sermons.html">sermões</a></li>
                                            <li><a href="events.html">eventos</a></li>
                                            <li><a href="blog.html">blog</a></li>
                                            <li><a href="contact.html">contato</a></li>
                                        *@
                                    </ul>
                                    <div class="search_button"><i class="fa fa-search" aria-hidden="true"></i></div>
                                </nav>

                                <!-- Hamburger -->

                                <div class="hamburger ml-auto">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Header Search Panel -->
            <div class="header_search_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="header_search_content d-flex flex-row align-items-center justify-content-end">
                                <form action="#" class="header_search_form">
                                    <input type="search" class="search_input" placeholder="Search" required="required">
                                    <button class="header_search_button d-flex flex-column align-items-center justify-content-center">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        @RenderBody()

    </div>

    <div class="menu d-flex flex-column align-items-center justify-content-center">
        <div class="menu_content">
            <div class="cross_1 d-flex flex-column align-items-center justify-content-center"><img src="http://inova.gov.br/wp-content/themes/inovagov2.1.1/img/default-thumbnail.jpg" alt=""></div>
            <form action="#" class="menu_search_form">
                <input type="search" class="menu_search_input" placeholder="Search" required="required">
                <button class="menu_search_button d-flex flex-column align-items-center justify-content-center">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </form>
            <nav class="menu_nav">
                <ul>
                    <li class="active"><a href="index.html">Home</a></li>
                    <li><a href="~/Views/Sobre/Sobre.cshtml">About</a></li>
                    <li><a href="sermons.html">Sermons</a></li>
                    <li><a href="events.html">Events</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </nav>
        </div>
        <div class="menu_close"><i class="fa fa-times" aria-hidden="true"></i></div>
    </div>


    <hr />

    @RenderSection("scripts", required: false)

    <!-- Footer -->
    <footer class="footer">
        @*        <div class="footer_background parallax-window" data-parallax="scroll" data-image-src="http://inova.gov.br/wp-content/themes/inovagov2.1.1/img/default-thumbnail.jpg" data-speed="0.8"></div>*@
        <div class="footer_background parallax-window" data-parallax="scroll" style="background-color:#2a1c1c" data-speed="0.8"></div>

        <div class="container">
            <div class="row">

                <!-- Footer - Contact -->
                <div class="col-lg-4 footer_col">
                    <div class="footer_column footer_contact_column">
                        <div class="footer_logo_container">
                            <a href="#">
                                <div class="footer_logo"><img src="http://inova.gov.br/wp-content/themes/inovagov2.1.1/img/default-thumbnail.jpg" alt=""></div>
                                <div class="footer_logo_text">projejto cinco solas</div>
                            </a>
                        </div>
                        <div class="footer_contact">
                            <ul>
                                <li><div><i class="fa fa-map-marker" aria-hidden="true"></i></div><span>Rua Eurico Sodré, 105 - Vila Medeiros</span></li>
                                <li><div><i class="fa fa-phone" aria-hidden="true"></i></div><span>+55 11 94527-5577</span></li>
                                <li><div><i class="fa fa-envelope" aria-hidden="true"></i></div><span>projetocincosolas@gmail.com</span></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- Footer - Links -->
                <div class="col-lg-4 footer_col">
                    <div class="footer_column footer_links">
                        <div class="footer_title">useful links</div>
                        <ul class="footer_links_list">
                            <li><a href="about.html"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Sobre nós</a></li>
                            <li><a href="contact.html"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Contato</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Doação</a></li>
                            <li><a href="blog.html"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Blog</a></li>
                            <li><a href="sermon.html"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Sermões</a></li>
                            <li><a href="events.html"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Eventos</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Serviço</a></li>
                            <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Mídia</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Footer - Subscribe -->
                <div class="col-lg-4 footer_col">
                    <div class="footer_column footer_subscribe">
                        <div class="footer_title">se inscrever</div>
                        <div class="footer_text">Junte-se à nossa newsletter semanal por e-mail para receber notícias, eventos e outros anúncios sobre o que está acontecendo na nossa igreja.</div>
                        <div class="footer_form_container">
                            <form action="#" class="footer_form">
                                <div>
                                    <input type="email" class="subscribe_input" placeholder="Digite seu e-mail" required="required">
                                    <button class="subscribe_button trans_200" type="submit">increver-se</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row copyright_row">
                <div class="col">
                    <div class="copyright_container d-flex flex-lg-row flex-column align-items-center justify-content-lg-start justify-content-center">
                        <div class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> Todos os direitos reservados | Este modelo é feito por <a href="#" target="_blank">Wellington Sales</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <div class="footer_social ml-lg-auto">
                            <ul>
                                <li><a href="https://www.facebook.com/I.A.R.Altar/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                @*<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>*@
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

ProjetoCincoSolas/ProjetoCincoSolas/Views/Shared/_Missao.cshtml
<div class="mission">
    <div class="mission_background parallax-window" data-parallax="scroll" data-image-src="../../Imagens/mission.jpg" data-speed="0.8"></div>
    <div class="mission_items d-flex flex-row flex-wrap align-items-start justify-content-start">

        <div class="mission_item text-center">
            <div class="mission_icon"><i class="fa fa-bell-o" aria-hidden="true"></i></div>
            <div class="mission_title">nossa missão</div>
            <div class="mission_text">Lorem ipsum dolor amet, consectet adipiscing doelit. Sed a mauri suscipita utrum arcu , gravida nisl. Interdum mante ipsum.</div>
        </div>

        <div class="mission_item text-center">
            <div class="mission_icon"><i class="fa fa-flag-o" aria-hidden="true"></i></div>
            <div class="mission_title">nossa comunidade</div>
            <div class="mission_text">Lorem ipsum dolor amet, consectet adipiscing doelit. Sed a mauri suscipita utrum arcu , gravida nisl. Interdum mante ipsum.</div>
        </div>

        <div class="mission_item text-center">
            <div class="mission_icon"><i class="fa fa-heart-o" aria-hidden="true"></i></div>
            <div class="mission_title">nossa crença</div>
            <div class="mission_text">Lorem ipsum dolor amet, consectet adipiscing doelit. Sed a mauri suscipita utrum arcu , gravida nisl. Interdum mante ipsum.</div>
        </div>

        <div class="mission_item text-center">
            <div class="mission_icon"><i class="fa fa-moon-o" aria-hidden="true"></i></div>
            <div class="mission_title">nossa fé</div>
            <div class="mission_text">Lorem ipsum dolor amet, consectet adipiscing doelit. Sed a mauri suscipita utrum arcu , gravida nisl. Interdum mante ipsum.</div>
        </div>

    </div>
</div>

ProjetoCincoSolas/ProjetoCincoSolas/Views/Shared/_Modal.cshtml
@*MODAL DE CONFIRMACAO*@
<div id="modal-confirmacao" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Atenção</h4>
            </div>
            <form>
                <input type="hidden" name="id" />
                <input type="hidden" name="identificacao" />

                <div class="modal-body">
                    <div class="row">
                        <div class="msg_confirmacao col-md-12" style="padding: 0 10px">
                            <p>Deseja realmente gerar uma nova senha para este usuário?</p>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary btn-confirmar" data-loading-text="Aguarde..." autocomplete="off">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@*FIM:MODAL CONFIRMACAO*@