ProjetoCincoSolas/ProjetoCincoSolas/Models/ComentarioBiblico.cs
namespace ProjetoCincoSolas.Models
{
    public class ComentarioBiblico : Entidade
    {
        public Comentario Comentario { get; set; }
        public LivroBiblia LivroBiblia { get; set; }
        public string ComentarioLivroBiblia { get; set; }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Controllers/ComentarioBiblicoController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using ProjetoCincoSolas.Business;
using ProjetoCincoSolas.DAO;
using ProjetoCincoSolas.Helpers;
using ProjetoCincoSolas.Models;
using ProjetoCincoSolas.ViewModel;

namespace ProjetoCincoSolas.Controllers
{
    public class ComentarioBiblicoController : Controller
    {
        private readonly ComentarioBiblicoNegocio _comentarioBiblicoNegocio;
        private readonly BaseRepository baseRepository;

        public ComentarioBiblicoController()
        {
            _comentarioBiblicoNegocio = new ComentarioBiblicoNegocio(baseRepository);
        }


        /// <summary>
        /// Carrega a página com os livros da Bíblia.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                var model = new ComentarioBiblicoViewModel
                {
                    Livros = _comentarioBiblicoNegocio.MontarComboLivros(),
                    Capitulos = new List<SelectListItem>()
                };

                return View(model);
            }
            catch (Exception e)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }


        /// <summary>
        /// Retorna lista de capítulos do livro selecionado da bíblia.
        /// </summary>
        /// <param name="idLivro"></param>
        /// <returns></returns>
        public JsonResult ListarCapitulos(int idLivro)
        {
            var retorno = new Retorno();

            try
            {
                var capitulos = _comentarioBiblicoNegocio.GetAllCapitulosLivro(idLivro);

                if (capitulos == null)
                {
                    retorno.AddErro("Erro na requisição");
                }

                return new JsonResult
                {
                    Data = new
                    {
                        capitulos,
                        retorno
                    }
                };
            }
            catch (Exception)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }

        /// <summary>
        /// Retorna lista de comentários da Bíblia.
        /// </summary>
        /// <param name="idLivro"></param>
        /// <param name="idCapitulo"></param>
        /// <returns></returns>
        public JsonResult ListarComentarios(int idLivro, int idCapitulo)
        {
            var retorno = new Retorno();

            try
            {
                var comentarios = _comentarioBiblicoNegocio.GetAllComentarios(idLivro, idCapitulo);

                if (comentarios == null)
                {
                    comentarios = new List<ComentarioBiblico>();

                    for (var i = 0; i < 10; i++)
                    {
                        var comentarioLivroBiblia = new ComentarioBiblico
                        {
                            Comentario = new Comentario
                            {
                                Id = i,
                                Nome = "Comentario" + i
                            },
                            LivroBiblia = new LivroBiblia
                            {
                                NumeroLivro = i
                            }
                        };
                        comentarios.Add(comentarioLivroBiblia);
                    }

                    retorno.AddErro("Erro na requisição");
                }

                return new JsonResult
                {
                    Data = new
                    {
                        comentarios,
                        retorno
                    }
                };
            }
            catch (Exception)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }

        // GET: ComentarioBiblico/ListarComentarios/5
        /// <summary>
        /// Retorna o comentário do livro da Bíblia e o capítulo selecionado.
        /// </summary>
        /// <returns></returns>
        public ActionResult ConsultarComentario(int idComentario, int idNumeroLivroBiblia, int idCapitulo)
        {
            var retorno = new Retorno();
            try
            {
                var comentariosBiblicos = _comentarioBiblicoNegocio.GetAllComentarioLivroBiblia(idComentario, idNumeroLivroBiblia, idCapitulo);

                if (comentariosBiblicos == null)
                {
                    retorno.AddErro("Erro na requisição");
                }

                return new JsonResult
                {
                    Data = new
                    {
                        comentariosBiblicos,
                        retorno
                    }
                };
            }
            catch (Exception)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }

        /// <summary>
        /// Retorna o comentário do livro da Bíblia e o capítulo selecionado.
        /// </summary>
        /// <returns></returns>
        public ActionResult ConsultarPalavra(string palavra)
        {
            var retorno = new Retorno();
            try
            {
                var palavras = _comentarioBiblicoNegocio.GetAllPalavra(palavra);

                if (palavras == null)
                {
                    retorno.AddErro("Erro na requisição");
                }

                return new JsonResult
                {
                    Data = new
                    {
                        palavras,
                        retorno
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            catch (Exception e)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }

        /// <summary>
        /// Retorna o comentário do livro da Bíblia e o capítulo selecionado.
        /// </summary>
        /// <returns></returns>
        public ActionResult ConsultarSignificadoPalavra(string id)
        {
            var retorno = new Retorno();
            try
            {
                var palavra = _comentarioBiblicoNegocio.GetSignificadoPalavra(Convert.ToInt32(id));

                if (string.IsNullOrEmpty(palavra))
                {
                    retorno.AddErro("Erro na requisição");
                }

                return new JsonResult
                {
                    Data = new
                    {
                        palavra,
                        retorno
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
            catch (Exception e)
            {
                throw new HttpException(403, "Acesso Negado");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Perolas()
        {
            return View();
        }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Controllers/PerolasController.cs
using ProjetoCincoSolas.Business;
using ProjetoCincoSolas.DAO;
using ProjetoCincoSolas.ViewModel;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace ProjetoCincoSolas.Views
{
    public class PerolasController : Controller
    {
        private readonly ComentarioBiblicoNegocio _comentarioBiblicoNegocio;

        public PerolasController()
        {
            _comentarioBiblicoNegocio = new ComentarioBiblicoNegocio();
        }

        // GET: Perolas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Perolas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Perolas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Perolas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Perolas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Perolas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Perolas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Perolas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Views/ComentarioBiblico/Index.cshtml
@model ProjetoCincoSolas.ViewModel.ComentarioBiblicoViewModel

@{
    ViewBag.Title = "Comentarios Bíblicos";
}

<link href="~/Content/about.css" rel="stylesheet" type="text/css" />
<link href="~/Content/about_responsive.css" rel="stylesheet" type="text/css" />
<link href="~/Content/tail.select-default.min.css" rel="stylesheet" />

<div class="home">
    <div class="home_background" style="background-image:url(../../Imagens/events.jpg)"></div>
    <div class="home_content">
        <div class="container">
            <div class="row">
                <div class="col d-flex flex-row align-items-center justify-content-start">
                    <div class="home_title">Comentários Bíblicos</div>
                    <div class="breadcrumbs ml-auto">
                        <ul>
                            <li><a href="index.html">Início</a></li>
                            <li>Comentários Bíblicos</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="container">
    <div class="alert alert-warning" role="alert" id="alert" style="display:none;">
        <span></span>
    </div>

    <div class="tabs-container w30">
        <ul class="tabs"></ul>
        <div id="tab-1" data-tab-title="Comentário" class="tab-content current">

            <form style="width: 100%; margin: 0 auto;" role="form">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>Livros:</label><br />
                        @Html.DropDownListFor(x => x.IdLivro, Model.Livros, "Selecione", new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-2">
                        <label>Capitulos:</label>
                        @Html.DropDownListFor(x => x.IdCapitulo, Model.Capitulos, "Selecione", new { @class = "form-control" })
                    </div>
                    <div>
                        <br /><br />
                        <label class="exibicao">Expandir: </label> <input type="checkbox" name="Expandir" value="Expandir" class="btn btn-primary mb-12">
                    </div>
                    <div class="form-group col-md-2">
                        <label> </label><br />
                        <button id="btnBuscar" class="btn btn-primary mb-2">
                            <i class="fa fa-search" aria-hidden="true"></i> Buscar
                        </button>
                    </div>
                </div>
            </form>

            <div class="comentario"></div>
        </div>

        <div id="tab-2" data-tab-title="Dicionário" class="tab-content">
            <div class="form-group col-md-4" style="width: 50%; margin: 0 auto;">
                <div class="input-group mb-3">
                    <input id="palavra-dicionario" type="text" class="form-control" placeholder="Digite a palavra" aria-label="Digite a palavra" aria-describedby="basic-addon2">
                </div>
            </div>
            <div class="dicionario"></div>
        </div>

        <div id="tab-3" data-tab-title="Dicionário" class="tab-content">
            <form style="width: 100%; margin: 0 auto;" role="form">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>Livros:</label><br />
                        @Html.DropDownListFor(x => x.IdLivro, Model.Livros, "Selecione", new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-2">
                        <label>Tags:</label>
                        @Html.DropDownListFor(x => x.IdTag, Model.Tags, "Selecione", new { @class = "form-control" })
                    </div>
                    <div>
                        <br /><br />
                        <label class="exibicao">Expandir: </label> <input type="checkbox" name="Expandir" value="Expandir" class="btn btn-primary mb-12">
                    </div>
                    <div class="form-group col-md-2">
                        <label> </label><br />
                        <button id="btnBuscar" class="btn btn-primary mb-2">
                            <i class="fa fa-search" aria-hidden="true"></i> Buscar
                        </button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
<!--Controle de abas-->
<script>
    $('.tab-content').each(function (i) {
        var tabTitle = $(this).data('tab-title');
        var current = $(this).hasClass('current') ? "current" : "";
        var newTab = $('<li class="tab-link"></li>');
        newTab.html(tabTitle)
            .addClass(current)
            .attr('data-tab', $(this).attr('id'));
        $('ul.tabs').append(newTab);
    });

    $(document).on('click', '.tabs li', function () {
        debugger;
        var tab_id = $(this).attr('data-tab');

        // Verifica se a aba atualiza a página
        if (tab_id === "tab-0") {
            location.reload();
        }

        $('.tabs li').removeClass('current');
        $('.tab-content').removeClass('current');

        $(this).addClass('current');
        $("#" + tab_id).addClass('current');
    });
</script>

<!--Seleção do livro-->
<script>
    $('#IdLivro').on('change', function () {

        var idLivro = $('#IdLivro').val();
        var idCapitulo = $('#IdCapitulo').val();

        $('#IdCapitulo').empty().prop('disabled', !idCapitulo);

        if (!idLivro) {
            return;
        }

        $.ajax({
            url: '@Url.Action("ListarCapitulos", "ComentarioBiblico")',
            data: { idLivro: idLivro },
            method: 'POST',
            dataType: 'json',
            cache: false,
            success: function (json) {
                if (!json.retorno.Erro) {
                    var combo = $('#IdCapitulo');
                    combo.empty();
                    $("#IdCapitulo").attr("disabled", false);

                    $.each(json.capitulos, function (element) {
                        combo.append(
                            $('<option>', {
                                value: element + 1,
                                html: element + 1
                            })
                        );
                    });
                }
                else {

                    for (var i = 0; i < json.retorno.Mensagens.length; i++) {
                        $('#alert').append(json.retorno.Mensagens[i] + "<br>");
                    }

                    $("#alert").fadeIn(700, function () {
                        setTimeout(function () {
                            $('#alert').fadeOut();
                        }, 1500);
                    });
                }
            }
        });
    }).change();
</script>

<!--Busca da lista de comentários-->
<script>
    $("#btnBuscar").on('click', (function (e) {
        e.preventDefault();

        var idLivro = $('#IdLivro').val();
        var idCapitulo = $('#IdCapitulo').val();

        $.ajax({
            url: '@Url.Action("ListarComentarios", "ComentarioBiblico")',
            data: { idLivro, idCapitulo },
            method: 'POST',
            dataType: 'json',
            cache: false,
            success: function (json) {
                if (!json.retorno.Erro) {
                    $('.comentario').html("");
                    for (var i = 0; i < json.comentarios.length; i++) {
                        var div2 = $('<div/>', {
                            css: {
                                'font-weight': 600
                            },
                            class: 'card-header',
                            id: json.comentarios[i].Comentario.Id
                        }).append('📖 ' + json.comentarios[i].Comentario.Nome);

                        var div1 = $('<div/>', {
                            class: 'card',
                            id: 'card-' + json.comentarios[i].Comentario.Id
                        }).append(div2);

                        $('.comentario').append(div1).append('<br>');
                    }
                }
                else {
                    for (var i = 0; i < json.retorno.Mensagens.length; i++) {
                        $('#alert').append(json.retorno.Mensagens[i] + '<br>');
                    }

                    $("#alert").fadeIn(700, function () {
                        setTimeout(function () {
                            $('#alert').fadeOut();
                        }, 1500);
                    });
                }
            }
        });

        return false;
    }));
</script>

<!--Busca de comentários clicado-->
<script>
    $('.comentario').on('click', '.card > .card-header', function (index) {
        if ($(this)[0].offsetParent.children[1] != null) {
            $(this).closest('.card').children('.card-body').animate({
                height: 'toggle'
            });
            return;
        }

        var idComentario = this.id;
        var idNumeroLivroBiblia = $('#IdLivro').val();
        var idCapitulo = $('#IdCapitulo').val();

        $.ajax({
            url: '@Url.Action("ConsultarComentario", "ComentarioBiblico")',
            data: { idComentario, idNumeroLivroBiblia, idCapitulo},
            method: 'POST',
            dataType: 'json',
            cache: false,
            success: function (json) {
                if (!json.retorno.Erro) {

                    var p = $('<p/>', {
                        class: 'card-text',
                    }).append(json.comentariosBiblicos[0].ComentarioLivroBiblia);

                    var div1 = $('<div/>', {
                        class: 'card-body',
                    }).append(p);

                    $('#card-' + json.comentariosBiblicos[0].Comentario.Id).append(div1);
                }
            }
        });
    });
</script>
<script>
    $('input[type=checkbox]').change(function () {
        this.checked ? $('.exibicao').html("Esconder: ") : $('.exibicao').html("Expandir: ");
        $('.card-header').click();
    });
</script>

<!--Busca da lista de palavras-->
<script>
$(function () {
    var minlength = 3;

    $("#palavra-dicionario").keyup(function () {
        var that = this,
            value = $(this).val();

        if (value.length >= minlength) {
            //if (searchRequest != null) searchRequest.abort();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("ConsultarPalavra", "ComentarioBiblico")',
                data: { 'palavra': value },
                dataType: 'json',
                success: function (json) {
                    if (!json.retorno.Erro) {
                        $('.dicionario').html("");
                        for (var i = 0; i < json.palavras.length; i++) {
                            var div2 = $('<div/>', {
                                css: {
                                    'font-weight': 600
                                },
                                class: 'card-header',
                                id: json.palavras[i].Id
                            }).append('📚 ' + json.palavras[i].Palavra + " - " + json.palavras[i].LivroDicionario);

                            var div1 = $('<div/>', {
                                class: 'card',
                                id: 'dic-card-' + json.palavras[i].Id
                            }).append(div2);

                            $('.dicionario').append(div1).append('<br>');
                        }
                    }
                }
            });
        }
    });
});
</script>

<!--Busca de comentários clicado-->
<script>
    $('.dicionario').on('click', '.card > .card-header', function (index) {
        var idDic = this.id;

        if ($(this)[0].offsetParent.children[1] != null) {
            $(this).closest('.card').children('.card-body').animate({
                height: 'toggle'
            });
            return;
        }

        $.ajax({
            url: '@Url.Action("ConsultarSignificadoPalavra", "ComentarioBiblico")',
            data: { id: this.id },
            method: 'POST',
            dataType: 'json',
            cache: false,
            success: function (json) {
                if (!json.retorno.Erro) {

                    var p = $('<p/>', {
                        class: 'card-text',
                    }).append(json.palavra);

                    var div1 = $('<div/>', {
                        class: 'card-body',
                    }).append(p);

                    $('#dic-card-' + idDic).append(div1);
                }
            }
        });
    });
</script>

<script src="~/Scripts/tail.select-full.min.js"></script>

<script>
    tail.select('#IdLivro', {
        search: true, descriptions: true, multiLimit: 15, hideSelected: true, hideDisabled: true, multiShowCount: false, multiContainer: true
    });
</script>

<style>
    .card-header {
        cursor: pointer;
        transition: 0.3s;
        border-left: 3px solid #dc3545;
    }

    button {
        cursor: pointer;
    }

    .card-header:hover {
        background-color: #f4e0e0;
        color: #852020;
        font-weight: 600;
    }

    .tabs-container {
        margin: 0 auto;
    }

    ul.tabs {
        margin: 0px;
        padding: 0px;
        list-style: none;
        border-bottom: 1px solid #d7d7d7;
    }

        ul.tabs li {
            background: none;
            color: #616161;
            display: inline-block;
            padding: 10px 15px;
            cursor: pointer;
        }

            ul.tabs li.current {
                color: #484848;
                border-bottom: 2px solid #F65314;
            }

    .tab-content {
        display: none;
        padding: 15px;
    }

        .tab-content.current {
            display: block;
        }

    .tab-link:hover {
        color: #FBBC05;
    }
</style>

ProjetoCincoSolas/ProjetoCincoSolas/Views/ComentarioBiblico/Perolas.cshtml
@model ProjetoCincoSolas.ViewModel.ComentarioBiblicoViewModel

@{
    ViewBag.Title = "Perolas";
}

<link href="~/Content/about.css" rel="stylesheet" type="text/css" />
<link href="~/Content/about_responsive.css" rel="stylesheet" type="text/css" />

<!-- Home -->
<div class="home">
    <div class="home_background" style="background-image:url(../../Imagens/events.jpg)"></div>
    <div class="home_content">
        <div class="container">
            <div class="row">
                <div class="col d-flex flex-row align-items-center justify-content-start">
                    <div class="home_title">Perolas</div>
                    <div class="breadcrumbs ml-auto">
                        <ul>
                            <li><a href="@Url.Action("Index", "Home")">Início</a></li>
                            <li>Perolas</li>
                        </ul>
                    </div>
                </div>
                <div class="event_container d-flex flex-lg-row flex-column align-items-center justify-content-start">
                    <div class="event_timer_container col-sm-12 col-md-12 col-lg-12">

                        <h4><i>"Cerca de 5 000 citações que servem de inspiração para comunicadores cristãos."</i></h4>
                        <div class="input-group pesquisa-curso">
                            <div class="input-group mb-3">
                                @Html.DropDownListFor(x => x.IdLivro, Model.Livros, "Selecione o autor", new { @class = "form-control col-md-3" })
                                <input type="text" class="form-control btnPesquisar" aria-label="Text input with dropdown button" placeholder="Pesquisar frase">
                                <div class="input-group-append">
                                    <button id="btnPesquisar" type="button" class="btn btn-outline-primary my-2 my-sm-0">Pesquisar</button>
                                </div>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />


<div class="container">
    <p> "Cerca de 5 000 citações que servem de inspiração para comunicadores cristãos.</p>

    <div class="input-group pesquisa-curso">
        <input type="text" class="form-control col-md-6 col-sm-6 btnPesquisar" placeholder="Pesquisar frase">
        <div class="input-group-append">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="button" id="btnPesquisar">Pesquisar</button>
        </div>
    </div>
</div>