ProjetoCincoSolas/ProjetoCincoSolas/Controllers/DevocionalDiarioController.cs
using ProjetoCincoSolas.DAO;
using System;
using System.Web.Mvc;

namespace ProjetoCincoSolas.Controllers
{
    public class DevocionalDiarioController : Controller
    {
        private readonly BuscaDevocionalRepository _buscaDevocional;

        public DevocionalDiarioController()
        {
            _buscaDevocional = new BuscaDevocionalRepository();
        }

        // GET: DesiringGod
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCodigoDevocional()
        {
            //var day = DateTime.Now.AddDays(1).Day;
            //var ano = DateTime.Now.AddYears(1).Year;

            var date = DateTime.Now.Day + "-de-" + GetMonth(DateTime.Now.Month);

            //Verificar dado retornar
            var codeEpisodio = _buscaDevocional.GetDevocional(date);

            return Json(codeEpisodio, JsonRequestBehavior.AllowGet);
        }

        private static string GetMonth(int mes)
        {
            switch (mes)
            {
                case 1:
                    return "Janeiro";
                case 2:
                    return "Fevereiro";
                case 3:
                    return "Março";
                case 4:
                    return "Abril";
                case 5:
                    return "Maio";
                case 6:
                    return "Junho";
                case 7:
                    return "Julho";
                case 8:
                    return "Agosto";
                case 9:
                    return "Setembro";
                case 10:
                    return "Outubro";
                case 11:
                    return "Novembro";
                default:
                    return "Dezembro";
            }
        }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Views/DevocionalDiario/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Alegria Inabalável - Jonh Piper";
}
<link href="~/Content/about.css" rel="stylesheet" type="text/css" />
<link href="~/Content/about_responsive.css" rel="stylesheet" type="text/css" />
<!-- Home -->
<div class="home">
    <div class="home_background" style="background-image:url(../../Imagens/events.jpg)"></div>
    <div class="home_content">
        <div class="container">
            <div class="row">
                <div class="col d-flex flex-row align-items-center justify-content-start">
                    <div class="home_title">Alegria Inabalável</div>
                    <div class="breadcrumbs ml-auto">
                        <ul>
                            <li><a href="@Url.Action("Index", "Home")">Início</a></li>
                            <li>Alegria Inabalável - Jonh Piper</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <br />
    <div class="team_name titulo"></div>
    <p class="descricao"></p>
    <br />
    <a href="#" class="btn btn-success" id="download"><i class="fa fa-download"></i> Baixar</a>
    <br />
    <br />

    <div id="link-player"></div>
</div>

<script type="text/javascript">
    $(function () {
        $.ajax({
            dataType: "json",
            type: "GET",
            url: "@Url.Action("GetCodigoDevocional", "DevocionalDiario")",
            success: function (dados) {
                $.ajax({
                    dataType: "json",
                    type: "GET",
                    url: "https://api.spreaker.com/episode/" + dados,
                    success: function (dados) {
                        if (dados) {
                            $('#download').attr("href", dados.response.episode.download_url);
                            $('.titulo').html(dados.response.episode.title);
                            $('.descricao').html(dados.response.episode.description);
                            $('<iframe>', {
                                src: 'https://widget.spreaker.com/player?episode_id=' + dados.response.episode.episode_id + '&theme=dark&autoplay=false&playlist=false',
                                width: '100%',
                                height: '200px',
                                frameborder: "0"
                            }).appendTo('#link-player');
                        }
                    }
                });
            }
        });
    });

    setTimeout(function() {
        $("#widget-container > div > div.player > div.player_content > button").click();
    }, 3000);
</script>