ProjetoCincoSolas/ProjetoCincoSolas/Controllers/PainelControleController.cs
using ProjetoCincoSolas.Helpers;
using ProjetoCincoSolas.Models;
using ProjetoCincoSolas.Servico;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoCincoSolas.Controllers
{
    public class PainelControleController : Controller
    {
        private readonly DevsServico _devsServico;

        public PainelControleController()
        {
            _devsServico = new DevsServico();
        }

        // GET: PainelControle
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SincronizarDados()
        {
            var listaPessoas = new List<PessoaImportadaDto>();
            var i = 1;
            while (i <= 10)
            {
                var getPessoa = _devsServico.SincronizarPessoa();
                var pessoaImportadaDto = JsonHelper.ToEntity<PessoaImportadaDto>(getPessoa);
                _devsServico.GravarQuery(pessoaImportadaDto);
                listaPessoas.Add(pessoaImportadaDto);
                i++;
            }

            return Json("Dados de pessoas sincronizados com sucesso!", JsonRequestBehavior.AllowGet);
        }
    }
}

ProjetoCincoSolas/ProjetoCincoSolas/Views/PainelControle/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="panel-controle">
        <img src="https://cdn3.iconfinder.com/data/icons/toolbar-people/512/user_refresh_man_male_profile_account_person-512.png" width="256px" /><br />
        <button type="button" class="btn btn-primary" id="sincronizar">
            Sincronizar
        </button>
        <br />
        <img src="~/Imagens/load.gif" class="load" />
        <label class="msg-retorno-service"></label><br />
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        $(".load").hide();
        $('#sincronizar').on('click', function () {
            $(this).button('loading');
            $(this).prop("disabled", true);
            $(this).html("Sincronizando...");

            $(".msg-retorno-service").html("");
            $(".load").show();
            $.ajax({
                type: "POST",
                url: '@Url.Action("SincronizarDados", "PainelControle")',
                success: function (resposta) {
                    $(".msg-retorno-service").fadeOut(0).html(resposta).fadeIn(200);
                    setTimeout(function () {
                        $('.msg-retorno-service').fadeOut('slow');
                    }, 2500);

                    $(this).button('reset');
                    $(".load").hide();
                },
                error: function (result) {
                    $(this).button('reset');
                    alert('error', result);
                }
            });
        });
    });
</script>